# https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-ds.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-es
  namespace: kube-system
  labels:
    k8s-app: fluentd-es
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fluentd-es
  labels:
    k8s-app: fluentd-es
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fluentd-es
  labels:
    k8s-app: fluentd-es
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  name: fluentd-es
  namespace: kube-system
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: fluentd-es
  apiGroup: ""

---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: fluentd-es
  name: fluentd-es-1.24
  namespace: kube-system
spec:
#  selector:
#    k8s-app: fluentd-es
#    version: v1.22
  template:
    metadata:
      labels:
        k8s-app: fluentd-es
        version: v1.24
    spec:
      serviceAccountName: fluentd-es
      containers:
        -
          command:
            - /bin/sh
            - "-c"
            - "/usr/sbin/td-agent 2>&1 >> /var/log/fluentd.log"
          image: "gcr.io/google_containers/fluentd-elasticsearch:1.24"
          imagePullPolicy: IfNotPresent
          name: fluentd-es
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            -
              mountPath: /var/log
              name: varlog
            -
              mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
      volumes:
        -
          hostPath:
            path: /var/log
          name: varlog
        -
          hostPath:
            path: /var/lib/docker/containers
          name: varlibdockercontainers
