apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: kibana-logging
  name: kibana-logging
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana-logging
  template:
    metadata:
      labels:
        k8s-app: kibana-logging
    spec:
      containers:
      - env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch-logging:9200
        image: blacktop/kibana:5.2
        #image: docker.elastic.co/kibana/kibana-oss:6.1.1
        #image: gcr.io/google_containers/kibana:latest
        imagePullPolicy: IfNotPresent
        name: kibana-logging
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
        resources: {}
